/** Names of the line icons exported from Figma ("COCO/Line/*" plus a few one-offs). */
export const ICON_NAMES = [
  'plus',
  'menu',
  'work',
  'sort',
  'note',
  'edit',
  'document',
  'status',
  'arrow-top',
  'arrow-bottom',
  'arrow-right',
  'arrow-top-right',
  'arrow-swap',
  'moon',
  'sun',
  'notification',
  'eye',
  'search',
  'close',
  'rotate-right',
  'filter',
  'calendar',
  'dollar',
  'check-double',
  'check',
  'close-bold',
  'chevron-right',
  'arrow-left',
  'chevron-left',
  'refresh-double',
  'time-circle',
  'git',
  // Bill of Materials (1:26716)
  'folder',
  'add-folder',
  'upload',
  'trash',
  'more-vertical',
  'edit-square',
  'alert-circle',
  // Suppliers, Knowledge & Analytics (1:26718)
  'chart',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
